apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-web
  template:
    metadata:
      labels:
        app: echo-web
    spec:
      containers:
      - name: echo-web
        image: gcr.io/[PROJECT_ID]/echo-app:v1
        ports:
        - containerPort: 8000

